# Generated by Django 4.0.5 on 2022-06-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_imgsproduct_product_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgsproduct',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgs_product', to='myapi.product'),
        ),
    ]
