# Generated by Django 4.0.5 on 2022-06-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgsproduct',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='s'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='Products'),
        ),
    ]
