# Generated by Django 4.0.5 on 2022-06-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_imgsproduct_img_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgsproduct',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Products'),
        ),
    ]
