# Generated by Django 4.0.5 on 2022-06-27 11:03

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_imgsproduct_headshot_ppoi_alter_imgsproduct_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='headshot_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='headshot_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='Products', verbose_name='Headshot'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='Products', verbose_name='Headshot'),
        ),
    ]
