# Generated by Django 4.0.5 on 2022-06-27 11:08

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_category_headshot_ppoi_product_headshot_ppoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgsproduct',
            name='img',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='ImgsProduct', verbose_name='Headshot'),
        ),
    ]
