# Generated by Django 4.0.5 on 2022-06-27 11:11

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_alter_imgsproduct_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgsproduct',
            name='img',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='Products', verbose_name='Headshot'),
        ),
    ]
